// The content of this file was generated by IBM Cloud
// Do not modify it as it might get overridden
module.exports = function(app){
	<% if(typeof spec !== 'undefined' && spec.applicationType === 'MS'){ %>
	require('./swagger')(app);
	<% } else {%>
	require('./public')(app);
	<% }%>
	require('./health')(app);
};


